baseURL = '/'
languageCode = 'en-us'
title = 'Tom Dobek'
theme = 'poison'

[params]
	brand = "Tom's blog"
	brand_image = "/images/profile.jpeg"
	dark_mode = true
	github_url = "https://github.com/tkdlabs"
	linkedin_url = "https://www.linkedin.com/in/tomasz-dobek-7115a64/"

	giscus = true
	giscus_repo = "tkdlabs/tkdlabs.github.io"
	giscus_repo_id = "R_kgDOMyNtjg"
	giscus_category = "General"
	giscus_category_id = "DIC_kwDOMyNtjs4DBxsu"
	giscus_mapping = "pathname"
	menu = [
		{Name = "About", URL = "/about/", HasChildren = false},
		{Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
		{Name = "Projects", URL = "/projects/", HasChildren = true, Limit = 10},
		{Name = "Tags", URL = "/tags/"},
		]

[taxonomy]
	series = 'series'
	tags = 'tags'

